// This file is generated by build:api script
// Placeholder - will be overwritten during build
export default async function handler() {
  throw new Error('This file should be built by build:api script');
}
